schema_version: 1

context:
  version: "2.14.0"

package:
  name: smt
  version: ${{ version }}

source:
  url: https://github.com/SMTorg/smt/archive/v${{ version }}.tar.gz
  sha256: fcb49ecaecda04da1b7d8fbfa0e5718bc48cda614de860530431037bb7d3f622
  file_name: smt-${{ version }}.tar.gz

build:
  number: 6
  skip: match(python, "<3.11")
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cython
    - if: build_platform != target_platform
      then: numpy
  host:
    - pip
    - setuptools
    - cython
    - python
    - numpy
  run:
    - python
    - numpy
    - pydoe
    - scikit-learn
    - jenn

tests:
  - python:
      imports:
        - smt
        - smt.surrogate_models
        - smt.kernels
        - smt.problems
        - smt.sampling_methods
        - smt.applications
      pip_check: false

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: surrogate model toolbox
  homepage: https://github.com/SMTorg/smt

extra:
  recipe-maintainers:
    - relf
