conda_forge_output_validation: true
conda_install_tool: pixi
conda_build_tool: rattler-build
build_platform:
  linux_64: linux_64
  linux_aarch64: linux_aarch64
  osx_64: osx_64
  osx_arm64: osx_arm64
  win_64: win_64
test: native_and_emulated
provider:
  osx_arm64: default
  linux_aarch64: default
